# Generated by Django 3.1.3 on 2020-11-28 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_order_at_station', models.CharField(max_length=200, null=True)),
                ('Deliver_my_order', models.CharField(max_length=200, null=True)),
                ('Insure_my_order', models.CharField(max_length=200, null=True)),
                ('same_day_delivery', models.CharField(max_length=200, null=True)),
                ('express_delivery', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='DeliveryInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.deliveryinfo'),
        ),
    ]
