# Generated by Django 3.1.3 on 2020-11-28 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201128_0646'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryInfo',
            new_name='OrderDeliveryInfo',
        ),
    ]
