# Generated by Django 3.1.3 on 2020-11-28 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201128_0648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdeliveryinfo',
            old_name='Deliver_my_order',
            new_name='deliver_my_order',
        ),
        migrations.RenameField(
            model_name='orderdeliveryinfo',
            old_name='Insure_my_order',
            new_name='insure_my_order',
        ),
    ]
