# Generated by Django 3.1.3 on 2020-12-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201208_0703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Shipping address'},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='session_key',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
