# Generated by Django 3.1.3 on 2020-11-28 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201128_0655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='DeliveryInfo',
            new_name='deliveryInfo',
        ),
    ]
