# Generated by Django 3.1.3 on 2020-12-09 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20201209_0427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='TIN_no',
            new_name='tin_number',
        ),
    ]
