# Generated by Django 3.1.3 on 2020-11-28 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20201128_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='create_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
