# Generated by Django 3.1.3 on 2020-11-30 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20201130_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
    ]
