# Generated by Django 3.1.3 on 2020-11-30 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_order_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='user',
            new_name='customer',
        ),
    ]
