# Generated by Django 3.1.2 on 2020-12-02 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20201202_1644'),
        ('store', '0012_product_discount'),
    ]

    operations = [
    ]
