# Generated by Django 3.1.2 on 2020-12-02 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_merge_20201202_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='label',
        ),
    ]
