# Generated by Django 3.1.2 on 2020-12-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20201202_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
