# Generated by Django 3.1.3 on 2020-12-26 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='session_key',
            new_name='device_id',
        ),
    ]
