# Generated by Django 3.1.3 on 2020-11-30 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tin',
        ),
    ]
