# Generated by Django 3.1.3 on 2020-12-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201226_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='device_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
